//! Complete hybrid KEM suites, layered on the combiner.
//!
//! The combiner in the crate root is a pure function of bytes: it derives the
//! shared secret once you already have both components' outputs. Getting
//! those outputs right is the other half of the problem, and it is the half
//! where the positional mistakes actually happen. A suite closes that gap: it
//! is key generation, encapsulation and decapsulation as one primitive, with
//! no six-argument call for a caller to misorder.
//!
//! # What is specified here, and by whom
//!
//! Three of the four suites are **specified by the CFRG** in
//! `draft-irtf-cfrg-concrete-hybrid-kems-04` section 4, which also publishes
//! test vectors in its Appendix B. Those vectors are the external anchor for
//! this module: they were produced by the specification's authors, not by
//! this project, and the conformance suite runs all thirty of them in Rust
//! and in TypeScript.
//!
//! - [`Suite::MlKem768P256`]
//! - [`Suite::MlKem768X25519`], which is X-Wing
//! - [`Suite::MlKem1024P384`]
//!
//! The fourth, [`Suite::MlKem1024X25519`], is **specified by this project and
//! by nobody else**. It is written up in `docs/mlkem1024-x25519.md` in the
//! repository, including the argument against using it. No external test
//! vectors exist for it, because no external specification of it exists. Its
//! vectors are regression pins generated by these implementations, and they
//! establish only that Rust and TypeScript agree and that the bytes have not
//! drifted. They establish nothing about whether the pairing is a good idea.
//!
//! [`Suite::provenance`] carries that distinction at runtime, and
//! [`Provenance`] documents it.
//!
//! # The construction
//!
//! All four use the **CG framework** of `draft-irtf-cfrg-hybrid-kems-12`
//! section 5.5: the C2PRI combiner with a nominal group as the traditional
//! component, SHAKE256 as the PRG and SHA3-256 as the KDF. In terms of this
//! crate's own API, every suite's shared secret is
//!
//! ```text
//! combine_c2pri(Kdf::Sha3_256, { ss_PQ, ss_T, ct_T, ek_T, label }, out)
//! ```
//!
//! The C2PRI form drops the ML-KEM ciphertext and encapsulation key from the
//! derivation, which is sound because ML-KEM is ciphertext second preimage
//! resistant. That is not this module's assumption to make lightly, and it is
//! not made lightly: it is the assumption the CFRG draft itself makes for all
//! three of its suites (section 5 of `concrete-hybrid-kems-04`, which cites
//! the X-Wing analysis for ML-KEM's C2PRI property). See
//! [`crate::C2priAssertion`].
//!
//! # Example
//!
//! ```
//! use hybrid_kem_combiner::suites::Suite;
//!
//! let suite = Suite::MlKem768X25519;
//!
//! // A seed you generated from a cryptographically secure source. With the
//! // `os-rng` feature, `suite.generate_key_pair()` does this for you.
//! let seed = [0x42u8; 32];
//! let recipient = suite.derive_key_pair(&seed).unwrap();
//!
//! // The sender holds only the encapsulation key.
//! let eseed = [0x17u8; 64];
//! let sent = suite
//!     .encapsulate_derand(recipient.encapsulation_key(), &eseed)
//!     .unwrap();
//!
//! // The recipient recovers the same secret from the ciphertext.
//! let received = suite
//!     .decapsulate(recipient.decapsulation_key(), sent.ciphertext())
//!     .unwrap();
//!
//! assert_eq!(sent.shared_secret(), received.as_slice());
//! ```
//!
//! # What is not promised
//!
//! The same disclaimer as the rest of the crate, and one more. The suites are
//! assembled from `libcrux-ml-kem`, `p256`, `p384` and `x25519-dalek`, and
//! this module's own code is the framework around them: the PRG expansion,
//! the seed split, the scalar sampling, the encodings and the combiner call.
//! That framework has had no external cryptographic review. The component
//! implementations have their own review status, which is theirs and not
//! this project's to claim.

use alloc::vec;
use alloc::vec::Vec;
use zeroize::{Zeroize, Zeroizing};

use crate::{
    combine_c2pri, C2priAssertion, C2priInputs, Ciphertext, EncapsulationKey, Kdf, Label,
    SharedSecret,
};

mod group;
mod mlkem;

use group::Group;
use mlkem::MlKem;

/// Every suite here has a 32 byte seed, which is also its decapsulation key.
pub const NSEED: usize = 32;
/// Every suite here produces a 32 byte shared secret.
pub const NSS: usize = 32;

/// Where a suite's definition comes from, and therefore how much a passing
/// test suite is worth.
///
/// This is not decoration. A vector that came from the specification's
/// authors proves conformance to something outside this project. A vector
/// this project generated proves only that the bytes have not changed since
/// the last time it generated them.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[non_exhaustive]
pub enum Provenance {
    /// Specified in `draft-irtf-cfrg-concrete-hybrid-kems-04` section 4, with
    /// test vectors published in its Appendix B. Those vectors are an
    /// external anchor and this crate is tested against them.
    CfrgConcreteHybridKems,
    /// Specified only by this project, in `docs/mlkem1024-x25519.md`.
    ///
    /// No standards body has defined this pairing, no external test vectors
    /// exist for it, and its absence from the CFRG drafts is a deliberate
    /// choice by their authors rather than an oversight. Read the document
    /// before using it: it argues both sides and it is possible to finish it
    /// and decide against.
    ThisProjectOnly,
}

/// A complete hybrid KEM: key generation, encapsulation and decapsulation.
///
/// See the [module documentation](self) for which suites are externally
/// specified and which one is not.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[non_exhaustive]
pub enum Suite {
    /// `MLKEM768-P256`: ML-KEM-768 with the P-256 nominal group.
    ///
    /// `draft-irtf-cfrg-concrete-hybrid-kems-04` section 4.1. Label
    /// `MLKEM768-P256`.
    MlKem768P256,
    /// `MLKEM768-X25519`: ML-KEM-768 with the Curve25519 nominal group.
    ///
    /// `draft-irtf-cfrg-concrete-hybrid-kems-04` section 4.2. Identical to
    /// X-Wing (`draft-connolly-cfrg-xwing-kem-10`), down to the six byte
    /// label `\.//^\`.
    MlKem768X25519,
    /// `MLKEM1024-P384`: ML-KEM-1024 with the P-384 nominal group.
    ///
    /// `draft-irtf-cfrg-concrete-hybrid-kems-04` section 4.3. Label
    /// `MLKEM1024-P384`.
    MlKem1024P384,
    /// `MLKEM1024-X25519`: ML-KEM-1024 with the Curve25519 nominal group.
    ///
    /// **Specified by this project and by nobody else.** See
    /// `docs/mlkem1024-x25519.md`, and [`Provenance::ThisProjectOnly`].
    /// Category 5 post-quantum without a NIST curve, at the cost of a
    /// traditional half that is not level matched and a suite that no
    /// standards body has reviewed.
    MlKem1024X25519,
}

/// Every suite, in a form you can iterate.
pub const SUITES: [Suite; 4] = [
    Suite::MlKem768P256,
    Suite::MlKem768X25519,
    Suite::MlKem1024P384,
    Suite::MlKem1024X25519,
];

/// The label of `MLKEM768-P256`, `draft-irtf-cfrg-concrete-hybrid-kems-04`
/// section 4.1: the ASCII string `MLKEM768-P256`.
const LABEL_MLKEM768_P256: &[u8] = b"MLKEM768-P256";
/// The label of `MLKEM768-X25519`, section 4.2, which is the X-Wing label:
/// the six bytes `5c2e2f2f5e5c`, ASCII `\.//^\`.
const LABEL_MLKEM768_X25519: &[u8] = &[0x5c, 0x2e, 0x2f, 0x2f, 0x5e, 0x5c];
/// The label of `MLKEM1024-P384`, section 4.3: the ASCII string
/// `MLKEM1024-P384`.
const LABEL_MLKEM1024_P384: &[u8] = b"MLKEM1024-P384";
/// The label of `MLKEM1024-X25519`, defined only by this project.
///
/// It is namespaced rather than spelled `MLKEM1024-X25519` on purpose. The
/// CFRG draft's label registry is managed and suffix free; this suite is not
/// in it and cannot be. If CFRG ever registers the bare name for a
/// construction that differs from this one in any way, two implementations
/// would derive different secrets from the same label and neither would get a
/// diagnosable error. A namespaced label makes that collision impossible.
/// The reasoning is in `docs/mlkem1024-x25519.md`.
const LABEL_MLKEM1024_X25519: &[u8] = b"quantakrypto.com/hybrid-kem/MLKEM1024-X25519/v1";

/// What can go wrong in a suite operation.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[non_exhaustive]
pub enum SuiteError {
    /// A byte string was not the length this suite requires.
    WrongLength {
        /// Which input, by name.
        what: &'static str,
        /// The length this suite requires, in bytes.
        expected: usize,
        /// The length that was supplied, in bytes.
        actual: usize,
    },
    /// A traditional-component byte string did not decode to a valid group
    /// element.
    ///
    /// `draft-irtf-cfrg-hybrid-kems-12` section 4.2: for groups such as P-256
    /// there exist byte strings of the right length that are not points, and
    /// a hybrid KEM whose group can fail this way is explicitly rejecting.
    /// This operates only on public data, so failing loudly is safe.
    InvalidGroupElement,
    /// A Diffie-Hellman exchange produced the identity element, which is not
    /// a shared secret.
    ///
    /// Unreachable for a valid prime-order point and a nonzero scalar. It is
    /// an error rather than a panic so that no panic path exists at all.
    DegenerateGroupElement,
    /// `RandomScalar` exhausted its seed without finding a valid scalar.
    ///
    /// `draft-irtf-cfrg-concrete-hybrid-kems-04` section 3.1.1 sizes the
    /// seeds so that this happens with probability below 2^-128 for P-256 and
    /// below 2^-192 for P-384.
    RejectionSamplingFailed,
    /// The ML-KEM encapsulation key failed the check of FIPS 203 section 7.2.
    ///
    /// `draft-connolly-cfrg-xwing-kem-10` section 3 requires this check on
    /// encapsulation and requires an error when it fails.
    InvalidMlKemEncapsulationKey,
    /// The combiner refused these inputs. Should be unreachable from a suite,
    /// whose lengths are all fixed and nonzero.
    Combiner(crate::Error),
    /// The operating system's random number generator failed.
    #[cfg(feature = "os-rng")]
    #[cfg_attr(docsrs, doc(cfg(feature = "os-rng")))]
    RandomnessUnavailable,
}

impl core::fmt::Display for SuiteError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            SuiteError::WrongLength {
                what,
                expected,
                actual,
            } => write!(f, "{what} must be {expected} bytes, got {actual}"),
            SuiteError::InvalidGroupElement => {
                f.write_str("a traditional component value is not a valid group element")
            }
            SuiteError::DegenerateGroupElement => {
                f.write_str("the Diffie-Hellman exchange produced the identity element")
            }
            SuiteError::RejectionSamplingFailed => f.write_str("RandomScalar exhausted its seed"),
            SuiteError::InvalidMlKemEncapsulationKey => {
                f.write_str("the ML-KEM encapsulation key failed the check of FIPS 203 section 7.2")
            }
            SuiteError::Combiner(inner) => write!(f, "combiner refused the inputs: {inner}"),
            #[cfg(feature = "os-rng")]
            SuiteError::RandomnessUnavailable => {
                f.write_str("the operating system random number generator failed")
            }
        }
    }
}

impl core::error::Error for SuiteError {}

impl From<crate::Error> for SuiteError {
    fn from(value: crate::Error) -> Self {
        SuiteError::Combiner(value)
    }
}

/// A hybrid key pair.
///
/// The decapsulation key is the seed, as
/// `draft-irtf-cfrg-hybrid-kems-12` section 5.2 specifies: the per-component
/// private keys are derived inside the suite, which is what prevents a
/// component key pair from being reused outside the hybrid.
pub struct KeyPair {
    decapsulation_key: Zeroizing<[u8; NSEED]>,
    encapsulation_key: Vec<u8>,
}

impl KeyPair {
    /// The 32 byte decapsulation key, which is the seed. Secret.
    pub fn decapsulation_key(&self) -> &[u8; NSEED] {
        &self.decapsulation_key
    }

    /// The encapsulation key, `concat(ek_PQ, ek_T)`. Public.
    pub fn encapsulation_key(&self) -> &[u8] {
        &self.encapsulation_key
    }

    /// Take ownership of the encapsulation key.
    pub fn into_encapsulation_key(self) -> Vec<u8> {
        self.encapsulation_key
    }
}

impl core::fmt::Debug for KeyPair {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("KeyPair")
            .field("decapsulation_key", &"[redacted; 32 bytes]")
            .field("encapsulation_key_len", &self.encapsulation_key.len())
            .finish()
    }
}

/// The output of encapsulation.
pub struct Encapsulation {
    shared_secret: Zeroizing<[u8; NSS]>,
    ciphertext: Vec<u8>,
}

impl Encapsulation {
    /// The 32 byte hybrid shared secret. Secret.
    pub fn shared_secret(&self) -> &[u8; NSS] {
        &self.shared_secret
    }

    /// The ciphertext, `concat(ct_PQ, ct_T)`. Public, and what you send.
    pub fn ciphertext(&self) -> &[u8] {
        &self.ciphertext
    }

    /// Take ownership of the ciphertext.
    pub fn into_ciphertext(self) -> Vec<u8> {
        self.ciphertext
    }
}

impl core::fmt::Debug for Encapsulation {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("Encapsulation")
            .field("shared_secret", &"[redacted; 32 bytes]")
            .field("ciphertext_len", &self.ciphertext.len())
            .finish()
    }
}

/// The fixed parameters of one suite.
struct Params {
    name: &'static str,
    label: &'static [u8],
    kem: MlKem,
    group: Group,
    provenance: Provenance,
}

impl Suite {
    const fn params(self) -> Params {
        match self {
            Suite::MlKem768P256 => Params {
                name: "MLKEM768-P256",
                label: LABEL_MLKEM768_P256,
                kem: MlKem::MlKem768,
                group: Group::P256,
                provenance: Provenance::CfrgConcreteHybridKems,
            },
            Suite::MlKem768X25519 => Params {
                name: "MLKEM768-X25519",
                label: LABEL_MLKEM768_X25519,
                kem: MlKem::MlKem768,
                group: Group::X25519,
                provenance: Provenance::CfrgConcreteHybridKems,
            },
            Suite::MlKem1024P384 => Params {
                name: "MLKEM1024-P384",
                label: LABEL_MLKEM1024_P384,
                kem: MlKem::MlKem1024,
                group: Group::P384,
                provenance: Provenance::CfrgConcreteHybridKems,
            },
            Suite::MlKem1024X25519 => Params {
                name: "MLKEM1024-X25519",
                label: LABEL_MLKEM1024_X25519,
                kem: MlKem::MlKem1024,
                group: Group::X25519,
                provenance: Provenance::ThisProjectOnly,
            },
        }
    }

    /// The suite's name, as its specification writes it.
    pub const fn name(self) -> &'static str {
        self.params().name
    }

    /// The domain separation label fed to the combiner.
    pub const fn label(self) -> &'static [u8] {
        self.params().label
    }

    /// Where this suite's definition comes from. Read [`Provenance`].
    pub const fn provenance(self) -> Provenance {
        self.params().provenance
    }

    /// `Nseed`: the length of a seed, and of a decapsulation key. 32, for
    /// every suite here.
    pub const fn nseed(self) -> usize {
        NSEED
    }

    /// `Ndk`: the length of a decapsulation key. 32, for every suite here,
    /// because the decapsulation key is the seed.
    pub const fn ndk(self) -> usize {
        NSEED
    }

    /// `Nek`: the length of an encapsulation key, `Nek_PQ + Nelem_T`.
    pub const fn nek(self) -> usize {
        let p = self.params();
        p.kem.nek() + p.group.nelem()
    }

    /// `Nct`: the length of a ciphertext, `Nct_PQ + Nelem_T`.
    pub const fn nct(self) -> usize {
        let p = self.params();
        p.kem.nct() + p.group.nelem()
    }

    /// `Nss`: the length of the hybrid shared secret. 32, for every suite
    /// here.
    pub const fn nss(self) -> usize {
        NSS
    }

    /// `Nrandom`: the length of the randomness accepted by
    /// [`Suite::encapsulate_derand`], `32 + Group_T.Nseed`.
    ///
    /// `draft-irtf-cfrg-hybrid-kems-12` Appendix A: the post-quantum
    /// component takes the first `PQ.Nrandom` bytes and the traditional
    /// component takes the last `T.Nrandom` bytes.
    pub const fn nrandom(self) -> usize {
        let p = self.params();
        p.kem.nrandom() + p.group.nseed()
    }

    /// `PRG.Nout`: how many bytes of SHAKE256 output the seed expands to,
    /// `KEM_PQ.Nseed + Group_T.Nseed`.
    const fn prg_nout(self) -> usize {
        let p = self.params();
        p.kem.nseed() + p.group.nseed()
    }

    /// `DeriveKeyPair(seed)`, `draft-irtf-cfrg-hybrid-kems-12` section 5.5.
    ///
    /// The seed is expanded with SHAKE256, split into a post-quantum half and
    /// a traditional half, and each component's key pair is derived from its
    /// half. The returned decapsulation key is the seed itself.
    ///
    /// # Errors
    ///
    /// [`SuiteError::WrongLength`] if `seed` is not 32 bytes, and
    /// [`SuiteError::RejectionSamplingFailed`] in the negligible case where
    /// the traditional seed contains no valid scalar.
    pub fn derive_key_pair(self, seed: &[u8]) -> Result<KeyPair, SuiteError> {
        let seed: &[u8; NSEED] = fixed(seed, "seed")?;
        let expanded = self.expand_decaps_key(seed)?;
        let mut encapsulation_key = Vec::with_capacity(self.nek());
        encapsulation_key.extend_from_slice(expanded.ek_pq.public_key_bytes());
        encapsulation_key.extend_from_slice(&expanded.ek_t);
        Ok(KeyPair {
            decapsulation_key: Zeroizing::new(*seed),
            encapsulation_key,
        })
    }

    /// `DecapsToEncaps(dk)`, `draft-irtf-cfrg-hybrid-kems-12` section 5.2:
    /// recompute the encapsulation key from the decapsulation key.
    ///
    /// # Errors
    ///
    /// The same as [`Suite::derive_key_pair`].
    pub fn encapsulation_key_from_decapsulation_key(
        self,
        dk: &[u8],
    ) -> Result<Vec<u8>, SuiteError> {
        Ok(self.derive_key_pair(dk)?.into_encapsulation_key())
    }

    /// `EncapsDerand(ek, randomness)`, `draft-irtf-cfrg-hybrid-kems-12`
    /// Appendix A.
    ///
    /// The first 32 bytes of `randomness` are the ML-KEM message `m`; the
    /// remaining `Group_T.Nseed` bytes are the seed of the ephemeral scalar.
    /// [`Suite::nrandom`] is the total.
    ///
    /// This is the form that reproduces the published test vectors. For real
    /// traffic use [`Suite::encapsulate`], or supply randomness from a
    /// cryptographically secure source.
    ///
    /// # Errors
    ///
    /// [`SuiteError::WrongLength`] if `ek` or `randomness` is the wrong size,
    /// [`SuiteError::InvalidMlKemEncapsulationKey`] if `ek_PQ` fails the
    /// check of FIPS 203 section 7.2, [`SuiteError::InvalidGroupElement`] if
    /// `ek_T` is not a group element, and
    /// [`SuiteError::RejectionSamplingFailed`] in the negligible case.
    pub fn encapsulate_derand(
        self,
        ek: &[u8],
        randomness: &[u8],
    ) -> Result<Encapsulation, SuiteError> {
        let p = self.params();
        if ek.len() != self.nek() {
            return Err(SuiteError::WrongLength {
                what: "encapsulation key",
                expected: self.nek(),
                actual: ek.len(),
            });
        }
        if randomness.len() != self.nrandom() {
            return Err(SuiteError::WrongLength {
                what: "randomness",
                expected: self.nrandom(),
                actual: randomness.len(),
            });
        }
        let (ek_pq, ek_t) = ek.split_at(p.kem.nek());
        let (m, seed_e) = randomness.split_at(p.kem.nrandom());

        // prepareEncapsG, section 5.1.1.
        let encapsulated = p.kem.encapsulate_derand(ek_pq, m)?;
        let ct_t = p.group.exp_base(seed_e)?;
        let ss_t = p.group.exp_and_extract(ek_t, seed_e)?;

        let mut shared_secret = Zeroizing::new([0u8; NSS]);
        self.combine(
            &encapsulated.shared_secret,
            &ss_t,
            &ct_t,
            ek_t,
            &mut shared_secret,
        )?;

        let mut ciphertext = Vec::with_capacity(self.nct());
        ciphertext.extend_from_slice(encapsulated.ciphertext_bytes());
        ciphertext.extend_from_slice(&ct_t);

        Ok(Encapsulation {
            shared_secret,
            ciphertext,
        })
    }

    /// `Decaps(dk, ct)`, `draft-irtf-cfrg-hybrid-kems-12` section 5.5.
    ///
    /// # Errors
    ///
    /// [`SuiteError::WrongLength`] if `dk` or `ct` is the wrong size, and
    /// [`SuiteError::InvalidGroupElement`] if `ct_T` is not a group element.
    /// A wrong ML-KEM ciphertext does not error: ML-KEM rejects implicitly,
    /// which yields a different shared secret rather than a signal.
    pub fn decapsulate(self, dk: &[u8], ct: &[u8]) -> Result<Zeroizing<[u8; NSS]>, SuiteError> {
        let p = self.params();
        let dk: &[u8; NSEED] = fixed(dk, "decapsulation key")?;
        if ct.len() != self.nct() {
            return Err(SuiteError::WrongLength {
                what: "ciphertext",
                expected: self.nct(),
                actual: ct.len(),
            });
        }
        let (ct_pq, ct_t) = ct.split_at(p.kem.nct());
        let expanded = self.expand_decaps_key(dk)?;

        // prepareDecapsG, section 5.1.1.
        let ss_pq = p.kem.decapsulate(&expanded.ek_pq, ct_pq)?;
        let ss_t = p.group.exp_and_extract(ct_t, &expanded.dk_t)?;

        let mut shared_secret = Zeroizing::new([0u8; NSS]);
        self.combine(&ss_pq, &ss_t, ct_t, &expanded.ek_t, &mut shared_secret)?;
        Ok(shared_secret)
    }

    /// `GenerateKeyPair()`: a fresh seed from the operating system, then
    /// [`Suite::derive_key_pair`].
    ///
    /// # Errors
    ///
    /// [`SuiteError::RandomnessUnavailable`] if the operating system's random
    /// number generator fails, plus the errors of
    /// [`Suite::derive_key_pair`].
    #[cfg(feature = "os-rng")]
    #[cfg_attr(docsrs, doc(cfg(feature = "os-rng")))]
    pub fn generate_key_pair(self) -> Result<KeyPair, SuiteError> {
        let mut seed = Zeroizing::new([0u8; NSEED]);
        getrandom::fill(seed.as_mut_slice()).map_err(|_| SuiteError::RandomnessUnavailable)?;
        self.derive_key_pair(seed.as_slice())
    }

    /// `Encaps(ek)`: fresh randomness from the operating system, then
    /// [`Suite::encapsulate_derand`].
    ///
    /// # Errors
    ///
    /// [`SuiteError::RandomnessUnavailable`] if the operating system's random
    /// number generator fails, plus the errors of
    /// [`Suite::encapsulate_derand`].
    #[cfg(feature = "os-rng")]
    #[cfg_attr(docsrs, doc(cfg(feature = "os-rng")))]
    pub fn encapsulate(self, ek: &[u8]) -> Result<Encapsulation, SuiteError> {
        let mut randomness = Zeroizing::new(vec![0u8; self.nrandom()]);
        getrandom::fill(randomness.as_mut_slice())
            .map_err(|_| SuiteError::RandomnessUnavailable)?;
        self.encapsulate_derand(ek, randomness.as_slice())
    }

    /// `expandDecapsKeyG(seed)`, `draft-irtf-cfrg-hybrid-kems-12` section
    /// 5.1.1, with SHAKE256 as the PRG.
    fn expand_decaps_key(self, seed: &[u8; NSEED]) -> Result<Expanded, SuiteError> {
        let p = self.params();
        let mut full = Zeroizing::new(vec![0u8; self.prg_nout()]);
        libcrux_sha3::shake256_ema(full.as_mut_slice(), seed);
        let (seed_pq, seed_t) = full.split_at(p.kem.nseed());

        let ek_pq = p.kem.derive_key_pair(seed_pq);
        let mut dk_t = Zeroizing::new(vec![0u8; seed_t.len()]);
        dk_t.copy_from_slice(seed_t);
        let ek_t = p.group.exp_base(&dk_t)?;
        Ok(Expanded { ek_pq, ek_t, dk_t })
    }

    /// `C2PRICombiner(ss_PQ, ss_T, ct_T, ek_T, Label)` with SHA3-256, which
    /// is `combine_c2pri` from the crate root.
    fn combine(
        self,
        ss_pq: &[u8],
        ss_t: &[u8],
        ct_t: &[u8],
        ek_t: &[u8],
        out: &mut [u8; NSS],
    ) -> Result<(), SuiteError> {
        combine_c2pri(
            Kdf::Sha3_256,
            &C2priInputs {
                pq_shared_secret: SharedSecret::new(ss_pq),
                traditional_shared_secret: SharedSecret::new(ss_t),
                traditional_ciphertext: Ciphertext::new(ct_t),
                traditional_encapsulation_key: EncapsulationKey::new(ek_t),
                label: Label::new(self.label()),
                // Every suite here uses the CG framework, whose C2PRI
                // combiner is sound because the post-quantum component is
                // ML-KEM. `draft-irtf-cfrg-concrete-hybrid-kems-04` section 5
                // makes exactly this assumption for its three suites, citing
                // the X-Wing analysis for ML-KEM's C2PRI property, and
                // `MLKEM1024-X25519` inherits it unchanged: ML-KEM-1024 is
                // the post-quantum half there too.
                assertion: C2priAssertion::assert_pq_kem_is_ciphertext_second_preimage_resistant(),
            },
            out,
        )
        .map_err(SuiteError::Combiner)
    }
}

/// The output of `expandDecapsKeyG`, minus `dk_PQ`, which lives inside
/// [`mlkem::MlKemKeyPair`].
struct Expanded {
    ek_pq: mlkem::MlKemKeyPair,
    ek_t: Vec<u8>,
    dk_t: Zeroizing<Vec<u8>>,
}

impl Drop for Expanded {
    fn drop(&mut self) {
        self.ek_t.zeroize();
    }
}

/// Borrow a slice as a fixed-size array, or name it in the error.
fn fixed<'a, const N: usize>(
    bytes: &'a [u8],
    what: &'static str,
) -> Result<&'a [u8; N], SuiteError> {
    bytes.try_into().map_err(|_| SuiteError::WrongLength {
        what,
        expected: N,
        actual: bytes.len(),
    })
}
