/**
 * Complete hybrid KEM suites, layered on the combiner.
 *
 * The combiner in the package root is a pure function of bytes: it derives
 * the shared secret once you already have both components' outputs. Getting
 * those outputs right is the other half of the problem, and it is the half
 * where the positional mistakes actually happen. A suite closes that gap: it
 * is key generation, encapsulation and decapsulation as one primitive, with
 * no six-argument call for a caller to misorder.
 *
 * # What is specified here, and by whom
 *
 * Three of the four suites are specified by the CFRG in
 * `draft-irtf-cfrg-concrete-hybrid-kems-04` section 4, which also publishes
 * test vectors in its Appendix B. Those vectors are the external anchor:
 * they were produced by the specification's authors, not by this project,
 * and the conformance suite runs all thirty of them in TypeScript and in
 * Rust.
 *
 * - {@link MLKEM768_P256}
 * - {@link MLKEM768_X25519}, which is X-Wing
 * - {@link MLKEM1024_P384}
 *
 * The fourth, {@link MLKEM1024_X25519}, is specified by this project and by
 * nobody else. It is written up in `docs/mlkem1024-x25519.md`, including the
 * argument against using it. No external test vectors exist for it, because
 * no external specification of it exists. Its vectors are regression pins
 * generated by these implementations, and they establish only that the two
 * languages agree and that the bytes have not drifted.
 *
 * Every suite carries a {@link Provenance} so that the distinction is
 * available at runtime and not only in prose.
 *
 * # The construction
 *
 * All four use the CG framework of `draft-irtf-cfrg-hybrid-kems-12` section
 * 5.5: the C2PRI combiner with a nominal group as the traditional component,
 * SHAKE256 as the PRG and SHA3-256 as the KDF. Every suite's shared secret is
 * this package's own `combineC2pri('sha3-256', ...)`.
 *
 * # What is not promised
 *
 * The same disclaimer as the rest of the package, and one more. The
 * arithmetic is `@noble/post-quantum`'s and `@noble/curves`'; this module's
 * code is the framework around it, implemented from the drafts. That
 * framework has had no external cryptographic review.
 *
 * @packageDocumentation
 */

import { x25519 } from '@noble/curves/ed25519.js';
import { p256, p384 } from '@noble/curves/nist.js';
import { shake256 } from '@noble/hashes/sha3.js';
import { randomBytes } from '@noble/hashes/utils.js';
import { ml_kem1024, ml_kem768 } from '@noble/post-quantum/ml-kem.js';

import {
  assertPqKemIsCiphertextSecondPreimageResistant,
  combineC2pri,
} from './index.js';

/** Every suite here has a 32 byte seed, which is also its decapsulation key. */
export const NSEED = 32;
/** Every suite here produces a 32 byte shared secret. */
export const NSS = 32;

/**
 * Where a suite's definition comes from, and therefore how much a passing
 * test suite is worth.
 *
 * - `cfrg-concrete-hybrid-kems`: specified in
 *   `draft-irtf-cfrg-concrete-hybrid-kems-04` section 4, with test vectors
 *   published in its Appendix B. Those vectors are an external anchor and
 *   this package is tested against them.
 * - `this-project-only`: specified in `docs/mlkem1024-x25519.md` and nowhere
 *   else. No standards body has defined the pairing, no external test
 *   vectors exist for it, and its absence from the CFRG drafts is a
 *   deliberate choice by their authors rather than an oversight.
 *
 * This is not decoration. A vector that came from the specification's authors
 * proves conformance to something outside this project. A vector this project
 * generated proves only that the bytes have not changed since the last time
 * it generated them.
 */
export type Provenance = 'cfrg-concrete-hybrid-kems' | 'this-project-only';

/** The name of a suite, as its specification writes it. */
export type SuiteName =
  | 'MLKEM768-P256'
  | 'MLKEM768-X25519'
  | 'MLKEM1024-P384'
  | 'MLKEM1024-X25519';

/** What kind of suite error occurred. */
export type SuiteErrorCode =
  | 'unknown-suite'
  | 'wrong-length'
  | 'invalid-group-element'
  | 'degenerate-group-element'
  | 'rejection-sampling-failed'
  | 'invalid-ml-kem-encapsulation-key';

/**
 * A suite error, thrown before any key material is returned.
 *
 * `code` mirrors the variants of the Rust crate's `SuiteError` enum.
 */
export class SuiteError extends Error {
  readonly code: SuiteErrorCode;

  constructor(code: SuiteErrorCode, message: string) {
    super(message);
    this.name = 'SuiteError';
    this.code = code;
  }
}

/** The byte lengths of a suite's values. */
export interface SuiteLengths {
  /** `Nseed`, the seed accepted by `deriveKeyPair`. */
  seed: number;
  /** `Ndk`, the decapsulation key, which is the seed. */
  decapsulationKey: number;
  /** `Nek`, `Nek_PQ + Nelem_T`. */
  encapsulationKey: number;
  /** `Nct`, `Nct_PQ + Nelem_T`. */
  ciphertext: number;
  /** `Nss`, the hybrid shared secret. */
  sharedSecret: number;
  /** `Nrandom`, the randomness accepted by `encapsulateDerand`. */
  randomness: number;
}

/** A hybrid key pair. The decapsulation key is the seed. */
export interface KeyPair {
  /** The 32 byte decapsulation key, which is the seed. Secret. */
  decapsulationKey: Uint8Array;
  /** `concat(ek_PQ, ek_T)`. Public. */
  encapsulationKey: Uint8Array;
}

/** The output of encapsulation. */
export interface Encapsulation {
  /** The 32 byte hybrid shared secret. Secret. */
  sharedSecret: Uint8Array;
  /** `concat(ct_PQ, ct_T)`. Public, and what you send. */
  ciphertext: Uint8Array;
}

/** A complete hybrid KEM. */
export interface HybridKemSuite {
  /** The suite's name, as its specification writes it. */
  readonly name: SuiteName;
  /** The domain separation label fed to the combiner. */
  readonly label: Uint8Array;
  /** Where this suite's definition comes from. Read {@link Provenance}. */
  readonly provenance: Provenance;
  /** The byte lengths of this suite's values. */
  readonly lengths: SuiteLengths;

  /**
   * `DeriveKeyPair(seed)`, `draft-irtf-cfrg-hybrid-kems-12` section 5.5.
   *
   * @throws {SuiteError} if `seed` is not `lengths.seed` bytes.
   */
  deriveKeyPair(seed: Uint8Array): KeyPair;

  /** `GenerateKeyPair()`: a fresh seed, then {@link deriveKeyPair}. */
  generateKeyPair(): KeyPair;

  /**
   * `DecapsToEncaps(dk)`, `draft-irtf-cfrg-hybrid-kems-12` section 5.2.
   *
   * @throws {SuiteError} on the same conditions as {@link deriveKeyPair}.
   */
  encapsulationKeyFromDecapsulationKey(
    decapsulationKey: Uint8Array,
  ): Uint8Array;

  /**
   * `EncapsDerand(ek, randomness)`, `draft-irtf-cfrg-hybrid-kems-12`
   * Appendix A. The first 32 bytes are the ML-KEM message; the rest is the
   * ephemeral scalar's seed.
   *
   * This is the form that reproduces the published test vectors. For real
   * traffic use {@link encapsulate}.
   *
   * @throws {SuiteError} on a wrong length, an invalid group element, or an
   *   ML-KEM encapsulation key that fails the check of FIPS 203 section 7.2.
   */
  encapsulateDerand(
    encapsulationKey: Uint8Array,
    randomness: Uint8Array,
  ): Encapsulation;

  /** `Encaps(ek)`: fresh randomness, then {@link encapsulateDerand}. */
  encapsulate(encapsulationKey: Uint8Array): Encapsulation;

  /**
   * `Decaps(dk, ct)`, `draft-irtf-cfrg-hybrid-kems-12` section 5.5.
   *
   * @throws {SuiteError} on a wrong length or an invalid group element. A
   *   wrong ML-KEM ciphertext does not throw: ML-KEM rejects implicitly.
   */
  decapsulate(decapsulationKey: Uint8Array, ciphertext: Uint8Array): Uint8Array;
}

// --- Nominal groups --------------------------------------------------------
//
// `draft-irtf-cfrg-hybrid-kems-12` section 4.2 defines a nominal group by
// `Exp`, `RandomScalar` and `ElementToSharedSecret`.
// `draft-irtf-cfrg-concrete-hybrid-kems-04` section 3.1 instantiates three of
// them. The parts that are easy to get wrong, and that no dependency does for
// you:
//
// - `RandomScalar` for the NIST curves is rejection sampling over successive
//   `Nscalar`-byte blocks of the seed, big endian, rejecting zero and
//   anything at or above the group order. It is not "reduce the seed mod n",
//   which would produce different keys from the same seed.
// - `RandomScalar` for Curve25519 is the identity function. The seed is the
//   scalar; RFC 7748's clamping happens inside `X25519`.
// - Group elements are uncompressed SEC1 points for the NIST curves, 65 and
//   97 bytes, and 32 byte u-coordinates for Curve25519.
// - `ElementToSharedSecret` is the x coordinate alone for the NIST curves,
//   32 and 48 bytes, not the whole point.

interface NominalGroup {
  readonly nseed: number;
  readonly nelem: number;
  readonly nss: number;
  /** `Exp(g, RandomScalar(seed))`. */
  expBase(seed: Uint8Array): Uint8Array;
  /** `ElementToSharedSecret(Exp(element, RandomScalar(seed)))`. */
  expAndExtract(element: Uint8Array, seed: Uint8Array): Uint8Array;
}

type NistCurve = typeof p256 | typeof p384;

function bytesToBigIntBE(bytes: Uint8Array): bigint {
  let value = 0n;
  for (const byte of bytes) value = (value << 8n) | BigInt(byte);
  return value;
}

function bigIntToBytesBE(value: bigint, length: number): Uint8Array {
  const out = new Uint8Array(length);
  let remaining = value;
  for (let i = length - 1; i >= 0; i -= 1) {
    out[i] = Number(remaining & 0xffn);
    remaining >>= 8n;
  }
  return out;
}

/**
 * Build the nominal group of a NIST curve.
 *
 * Both curves have the same algorithms and differ only in their constants,
 * so they come from one definition. Writing them out twice would be two
 * places for the encoding to drift.
 */
function nistGroup(
  curve: NistCurve,
  nseed: number,
  what: string,
): NominalGroup {
  const point = curve.Point;
  const nscalar = point.Fn.BYTES;
  const nelem = 1 + 2 * point.Fp.BYTES;
  const order = point.CURVE().n;

  /**
   * `RandomScalar(seed)`, `draft-irtf-cfrg-concrete-hybrid-kems-04` section
   * 3.1.1: successive `Nscalar`-byte blocks read as big-endian integers,
   * until one is nonzero and below the group order.
   */
  const randomScalar = (seed: Uint8Array): bigint => {
    for (let start = 0; start + nscalar <= seed.length; start += nscalar) {
      const candidate = bytesToBigIntBE(seed.subarray(start, start + nscalar));
      // `draft-irtf-cfrg-hybrid-kems-12` section 4.2 says RandomScalar MUST
      // NOT return a zero scalar.
      if (candidate !== 0n && candidate < order) return candidate;
    }
    throw new SuiteError(
      'rejection-sampling-failed',
      'RandomScalar exhausted its seed',
    );
  };

  const decode = (bytes: Uint8Array) => {
    // The length is checked first so that a compressed point, which SEC1
    // would happily decode, is refused: the framework's fixed-length encoding
    // is what makes the combiner's unprefixed concatenation unambiguous.
    if (bytes.length !== nelem) {
      throw new SuiteError(
        'wrong-length',
        `${what} must be ${nelem} bytes, got ${bytes.length}`,
      );
    }
    if (bytes[0] !== 0x04) {
      throw new SuiteError(
        'invalid-group-element',
        `${what} is not an uncompressed SEC1 point`,
      );
    }
    try {
      return point.fromBytes(bytes);
    } catch {
      throw new SuiteError(
        'invalid-group-element',
        `${what} is not a valid group element`,
      );
    }
  };

  return {
    nseed,
    nelem,
    nss: point.Fp.BYTES,
    expBase(seed) {
      const product = point.BASE.multiply(randomScalar(seed));
      if (product.is0()) {
        throw new SuiteError(
          'degenerate-group-element',
          'Exp produced the identity element',
        );
      }
      return product.toBytes(false);
    },
    expAndExtract(element, seed) {
      const product = decode(element).multiply(randomScalar(seed));
      if (product.is0()) {
        throw new SuiteError(
          'degenerate-group-element',
          'the Diffie-Hellman exchange produced the identity element',
        );
      }
      // ElementToSharedSecret: the x coordinate alone, as an Nss-byte string.
      return bigIntToBytesBE(product.toAffine().x, point.Fp.BYTES);
    },
  };
}

/** The Curve25519 field modulus, `2^255 - 19`. */
const P25519 = (1n << 255n) - 19n;

/** Clears bit 255, which is RFC 7748 section 5's mask of the last byte. */
const MASK255 = (1n << 255n) - 1n;

/**
 * The u-coordinates whose `X25519` output is the all-zero string.
 *
 * These are exactly the points of order dividing 8, on the curve and on its
 * quadratic twist, and there are exactly five of them. It is the same list
 * libsodium and post-CVE-2017-0379 Libgcrypt carry, and the same one
 * `@noble/curves` rejects on.
 *
 * The list is complete, and the argument is short enough to write down.
 * X-only doubling sends `u` to `(u^2 - 1)^2 / 4u(u^2 + Au + 1)`, so:
 *
 * - order dividing 2 needs `4u(u^2 + Au + 1) = 0`. `A^2 - 4` is a
 *   non-residue mod `p`, so the quadratic has no root and only `u = 0`
 *   qualifies.
 * - order dividing 4 additionally needs `(u^2 - 1)^2 = 0`, giving `u = 1`
 *   and `u = p - 1`.
 * - order dividing 8 additionally needs `dbl(u)` to be `1` or `p - 1`. Over
 *   `F_p` the first quartic has exactly two roots, listed below, and the
 *   second has none.
 *
 * Curve25519 has cofactor 8 and its twist cofactor 4, so nothing of larger
 * order can be sent to zero by an RFC 7748 clamped scalar: such a scalar is
 * `8m` with `2^251 <= m < 2^252`, which is smaller than either prime
 * subgroup order, so it is never a multiple of one.
 */
const X25519_DEGENERATE_U: ReadonlySet<bigint> = new Set([
  0n,
  1n,
  P25519 - 1n,
  325606250916557431795983626356110631294008115727848805560023387167927233504n,
  39382357235489614581723060781553021112529911719440698176882885853963445705823n,
]);

/**
 * Whether `X25519(k, element)` is the all-zero string for every RFC 7748
 * clamped scalar `k`.
 *
 * The decoding is RFC 7748 section 5's `decodeUCoordinate`: mask the most
 * significant bit of the last byte, then read little endian and reduce, so
 * that the non-canonical encodings of `0` and `1` are recognised too.
 */
function isDegenerateX25519U(element: Uint8Array): boolean {
  const u = bytesToBigIntBE(Uint8Array.from(element).reverse()) & MASK255;
  return X25519_DEGENERATE_U.has(u % P25519);
}

const CURVE25519: NominalGroup = {
  nseed: 32,
  nelem: 32,
  nss: 32,
  expBase(seed) {
    requireLength(seed, 32, 'Curve25519 scalar');
    return x25519.scalarMultBase(seed);
  },
  expAndExtract(element, seed) {
    requireLength(seed, 32, 'Curve25519 scalar');
    requireLength(element, 32, 'Curve25519 element');
    // No all-zero check *and no all-zero rejection*. Every 32 byte string is
    // a valid Curve25519 u-coordinate, X-Wing's Encapsulate and Decapsulate
    // (draft-connolly-cfrg-xwing-kem-10 sections 5.4 and 5.5) do not check,
    // and rejecting here would make this implementation disagree with
    // conforming peers on exactly the inputs an attacker chooses.
    // Contributory behaviour is an explicit non-goal of
    // draft-irtf-cfrg-hybrid-kems-12 section 8.
    //
    // Saying that is not enough on its own, which is the whole point of this
    // block. `@noble/curves`' `x25519.scalarMult` refuses the low-order
    // u-coordinates rather than returning the all-zero output RFC 7748
    // section 6.1 permits detecting from, and it does so for a defensible
    // reason of its own: rejecting before the ladder avoids running 255
    // rounds against the long-term secret for an attacker's benefit. That is
    // the right default for a bare ECDH API and the wrong one here, so the
    // refusal is turned back into the all-zero output the suite specifies.
    //
    // The recovery never guesses. `isDegenerateX25519U` decides, from the
    // input alone and independently of the dependency, whether the output is
    // mathematically the all-zero string; anything else `scalarMult` throws
    // is rethrown untouched. A failure for an unrelated reason therefore
    // cannot be laundered into a silently wrong shared secret, and a future
    // version of the dependency that changed its error message, or stopped
    // throwing at all, would not change this function's output on any input.
    try {
      return x25519.scalarMult(seed, element);
    } catch (cause) {
      if (isDegenerateX25519U(element)) return new Uint8Array(32);
      throw cause;
    }
  },
};

const P256_GROUP = nistGroup(p256, 128, 'P-256 element');
const P384_GROUP = nistGroup(p384, 48, 'P-384 element');

// --- ML-KEM ---------------------------------------------------------------
//
// `draft-irtf-cfrg-concrete-hybrid-kems-04` section 3.2.1 maps FIPS 203 onto
// the framework's KEM interface. `DeriveKeyPair(seed)` is
// `KeyGen_internal(seed[0:32], seed[32:64])`, so the KEM's `Nseed` is 64, not
// 32, and `EncapsDerand` is `Encaps_internal` with `Nrandom` 32.

interface PqKem {
  readonly nseed: number;
  readonly nek: number;
  readonly nct: number;
  readonly nrandom: number;
  deriveKeyPair(seed: Uint8Array): { secretKey: Uint8Array; publicKey: Uint8Array };
  encapsulateDerand(
    ek: Uint8Array,
    message: Uint8Array,
  ): { sharedSecret: Uint8Array; ciphertext: Uint8Array };
  decapsulate(secretKey: Uint8Array, ciphertext: Uint8Array): Uint8Array;
}

function mlKem(kem: typeof ml_kem768, nek: number, nct: number): PqKem {
  return {
    nseed: 64,
    nek,
    nct,
    nrandom: 32,
    deriveKeyPair(seed) {
      return kem.keygen(seed);
    },
    encapsulateDerand(ek, message) {
      let result;
      try {
        // The encapsulation key check of FIPS 203 section 7.2 happens here.
        // draft-connolly-cfrg-xwing-kem-10 section 3 requires that a failure
        // be an error rather than a silently derived key.
        result = kem.encapsulate(ek, message);
      } catch {
        throw new SuiteError(
          'invalid-ml-kem-encapsulation-key',
          'the ML-KEM encapsulation key failed the check of FIPS 203 section 7.2',
        );
      }
      return {
        sharedSecret: result.sharedSecret,
        ciphertext: result.cipherText,
      };
    },
    decapsulate(secretKey, ciphertext) {
      // ML-KEM rejects implicitly: a ciphertext that does not decrypt yields
      // a pseudorandom shared secret rather than an error, which is what
      // keeps the KEM IND-CCA.
      return kem.decapsulate(ciphertext, secretKey);
    },
  };
}

const MLKEM768: PqKem = mlKem(ml_kem768, 1184, 1088);
const MLKEM1024: PqKem = mlKem(ml_kem1024, 1568, 1568);

// --- Suite construction ----------------------------------------------------

function requireLength(value: unknown, expected: number, what: string): void {
  if (!(value instanceof Uint8Array)) {
    throw new TypeError(`${what} must be a Uint8Array`);
  }
  if (value.length !== expected) {
    throw new SuiteError(
      'wrong-length',
      `${what} must be ${expected} bytes, got ${value.length}`,
    );
  }
}

function concat(a: Uint8Array, b: Uint8Array): Uint8Array {
  const out = new Uint8Array(a.length + b.length);
  out.set(a, 0);
  out.set(b, a.length);
  return out;
}

function makeSuite(
  name: SuiteName,
  label: Uint8Array,
  provenance: Provenance,
  kem: PqKem,
  group: NominalGroup,
): HybridKemSuite {
  const lengths: SuiteLengths = {
    seed: NSEED,
    decapsulationKey: NSEED,
    encapsulationKey: kem.nek + group.nelem,
    ciphertext: kem.nct + group.nelem,
    sharedSecret: NSS,
    randomness: kem.nrandom + group.nseed,
  };
  const prgNout = kem.nseed + group.nseed;

  /** `expandDecapsKeyG(seed)`, section 5.1.1, with SHAKE256 as the PRG. */
  const expandDecapsKey = (seed: Uint8Array) => {
    requireLength(seed, NSEED, 'seed');
    const full = shake256(seed, { dkLen: prgNout });
    const seedPq = full.subarray(0, kem.nseed);
    const seedT = full.subarray(kem.nseed, prgNout);
    const pq = kem.deriveKeyPair(seedPq);
    return {
      pqSecretKey: pq.secretKey,
      pqPublicKey: pq.publicKey,
      tScalarSeed: seedT,
      tElement: group.expBase(seedT),
    };
  };

  /** `C2PRICombiner(ss_PQ, ss_T, ct_T, ek_T, Label)` with SHA3-256. */
  const combine = (
    ssPq: Uint8Array,
    ssT: Uint8Array,
    ctT: Uint8Array,
    ekT: Uint8Array,
  ): Uint8Array =>
    combineC2pri(
      'sha3-256',
      {
        pqSharedSecret: ssPq,
        traditionalSharedSecret: ssT,
        traditionalCiphertext: ctT,
        traditionalEncapsulationKey: ekT,
        label,
        // Every suite here uses the CG framework, whose C2PRI combiner is
        // sound because the post-quantum component is ML-KEM.
        // draft-irtf-cfrg-concrete-hybrid-kems-04 section 5 makes exactly
        // this assumption for its three suites, citing the X-Wing analysis
        // for ML-KEM's C2PRI property, and MLKEM1024-X25519 inherits it
        // unchanged: ML-KEM-1024 is the post-quantum half there too.
        assertion: assertPqKemIsCiphertextSecondPreimageResistant(),
      },
      NSS,
    );

  return {
    name,
    label,
    provenance,
    lengths,

    deriveKeyPair(seed) {
      const expanded = expandDecapsKey(seed);
      return {
        decapsulationKey: Uint8Array.from(seed),
        encapsulationKey: concat(expanded.pqPublicKey, expanded.tElement),
      };
    },

    generateKeyPair() {
      return this.deriveKeyPair(randomBytes(NSEED));
    },

    encapsulationKeyFromDecapsulationKey(decapsulationKey) {
      return this.deriveKeyPair(decapsulationKey).encapsulationKey;
    },

    encapsulateDerand(encapsulationKey, randomness) {
      requireLength(
        encapsulationKey,
        lengths.encapsulationKey,
        'encapsulation key',
      );
      requireLength(randomness, lengths.randomness, 'randomness');

      const ekPq = encapsulationKey.subarray(0, kem.nek);
      const ekT = encapsulationKey.subarray(kem.nek);
      const message = randomness.subarray(0, kem.nrandom);
      const seedE = randomness.subarray(kem.nrandom);

      // prepareEncapsG, section 5.1.1.
      const pq = kem.encapsulateDerand(ekPq, message);
      const ctT = group.expBase(seedE);
      const ssT = group.expAndExtract(ekT, seedE);

      return {
        sharedSecret: combine(pq.sharedSecret, ssT, ctT, ekT),
        ciphertext: concat(pq.ciphertext, ctT),
      };
    },

    encapsulate(encapsulationKey) {
      return this.encapsulateDerand(
        encapsulationKey,
        randomBytes(lengths.randomness),
      );
    },

    decapsulate(decapsulationKey, ciphertext) {
      requireLength(ciphertext, lengths.ciphertext, 'ciphertext');
      const expanded = expandDecapsKey(decapsulationKey);
      const ctPq = ciphertext.subarray(0, kem.nct);
      const ctT = ciphertext.subarray(kem.nct);

      // prepareDecapsG, section 5.1.1.
      const ssPq = kem.decapsulate(expanded.pqSecretKey, ctPq);
      const ssT = group.expAndExtract(ctT, expanded.tScalarSeed);
      return combine(ssPq, ssT, ctT, expanded.tElement);
    },
  };
}

const encoder = new TextEncoder();

/**
 * `MLKEM768-P256`: ML-KEM-768 with the P-256 nominal group.
 *
 * `draft-irtf-cfrg-concrete-hybrid-kems-04` section 4.1. Label
 * `MLKEM768-P256`.
 */
export const MLKEM768_P256: HybridKemSuite = makeSuite(
  'MLKEM768-P256',
  encoder.encode('MLKEM768-P256'),
  'cfrg-concrete-hybrid-kems',
  MLKEM768,
  P256_GROUP,
);

/**
 * `MLKEM768-X25519`: ML-KEM-768 with the Curve25519 nominal group.
 *
 * `draft-irtf-cfrg-concrete-hybrid-kems-04` section 4.2. Identical to X-Wing
 * (`draft-connolly-cfrg-xwing-kem-10`), down to the six byte label.
 */
export const MLKEM768_X25519: HybridKemSuite = makeSuite(
  'MLKEM768-X25519',
  Uint8Array.from([0x5c, 0x2e, 0x2f, 0x2f, 0x5e, 0x5c]),
  'cfrg-concrete-hybrid-kems',
  MLKEM768,
  CURVE25519,
);

/**
 * `MLKEM1024-P384`: ML-KEM-1024 with the P-384 nominal group.
 *
 * `draft-irtf-cfrg-concrete-hybrid-kems-04` section 4.3. Label
 * `MLKEM1024-P384`.
 */
export const MLKEM1024_P384: HybridKemSuite = makeSuite(
  'MLKEM1024-P384',
  encoder.encode('MLKEM1024-P384'),
  'cfrg-concrete-hybrid-kems',
  MLKEM1024,
  P384_GROUP,
);

/**
 * `MLKEM1024-X25519`: ML-KEM-1024 with the Curve25519 nominal group.
 *
 * **Specified by this project and by nobody else.** See
 * `docs/mlkem1024-x25519.md`. Category 5 post-quantum without a NIST curve,
 * at the cost of a traditional half that is not level matched and a suite
 * that no standards body has reviewed.
 *
 * The label is namespaced rather than the bare name `MLKEM1024-X25519`: the
 * hybrid KEM label registry is managed and suffix free, this suite cannot be
 * in it, and a future registration of the bare name for a different
 * construction would make two implementations derive different secrets from
 * the same label with no diagnosable error.
 */
export const MLKEM1024_X25519: HybridKemSuite = makeSuite(
  'MLKEM1024-X25519',
  encoder.encode('quantakrypto.com/hybrid-kem/MLKEM1024-X25519/v1'),
  'this-project-only',
  MLKEM1024,
  CURVE25519,
);

/** Every suite, keyed by name. */
export const SUITES: Readonly<Record<SuiteName, HybridKemSuite>> = Object.freeze(
  {
    'MLKEM768-P256': MLKEM768_P256,
    'MLKEM768-X25519': MLKEM768_X25519,
    'MLKEM1024-P384': MLKEM1024_P384,
    'MLKEM1024-X25519': MLKEM1024_X25519,
  },
);

/**
 * Look a suite up by the name its specification uses.
 *
 * @throws {SuiteError} if there is no such suite. It throws rather than
 *   returning `undefined` because a silently missing suite in a protocol
 *   negotiation is worse than a loud one.
 */
export function getSuite(name: string): HybridKemSuite {
  const suite = (SUITES as Record<string, HybridKemSuite | undefined>)[name];
  if (suite === undefined) {
    throw new SuiteError('unknown-suite', `unknown hybrid KEM suite: ${name}`);
  }
  return suite;
}
